logging:
  level:
    root: INFO
    
server:
  port: 8791
  servlet:
      context-path: /fitness
      
spring:
  profiles: default
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: Europe/Berlin
    default-property-inclusion: non-null
    serialization:
      write-date-keys-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false